<?php 
header('Access-Control-Allow-Origin: *');
   date_default_timezone_set('Africa/Lagos');
	
 require_once('config/DB_config.php');
require_once('class_file.php');
require_once('fcm-send-function.php');
require_once('view-application-details.php');
 
 


$fcm = new FCM(); 
$fcmSend = new fcm();

$myName = new Name();


$json =  json_decode(file_get_contents('php://input'), true);


 
$phone_number = $json['phone_number']; 
$channel = $json['channel']; 
$wallet_number = $json['wallet_number']; 
$wynkid = $json['wynkid']; 

//$amount = $json['amount']; 
$amount = str_replace(",","",$json['amount']) ;
 
 /*

$phone_number = "08035538658";
$wynkid = "WYNK74654117"; 
$channel = "MTN"; 
$wallet_number = "4438308235"; 
$amount = 30; 
*/
  

$clientReference = date('dmY').rand(234,62662);
if(!empty($wallet_number))
{
	
	 
        
       $remita_url = $myName->showName($conn, "SELECT `remita_url` FROM `application` WHERE 1");	
     //  $remita_username = $myName->showName($conn, "SELECT `remita_username` FROM `application` WHERE 1");		
      // $remita_password = $myName->showName($conn, "SELECT `remita_password` FROM `application` WHERE 1");		
       $pin = $myName->showName($conn, "SELECT `pin` FROM `user_unit` WHERE `account_number` = '$wynkid'");		
       $wynk_name = $myName->showName($conn, "SELECT `name` FROM `user_unit` WHERE `account_number` = '$wynkid'");		
       
       $remita_username = $myName->showName($conn, "SELECT `phone` FROM `wallet_info` WHERE `registeredby` = '$wynkid' AND `phone` != ''  LIMIT 1 ");
	$remita_password  = $myName->showName($conn, "SELECT `password` FROM `wallet_info` WHERE `registeredby` = '$wynkid' AND `password` != ''  LIMIT 1");
 

   $remita_scheme = $myName->showName($conn, "SELECT `remita_scheme` FROM `application` WHERE 1");	
$url = $remita_url."/authenticate";

        
       
$curl = curl_init($url);
curl_setopt($curl, CURLOPT_URL, $url);
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

$headers = array(
   "accept: application/json",
   "Content-Type: application/json",
);
curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);

$data = <<<DATA
{
  "password": "$remita_password",
  "rememberMe": true,
  "username": "$remita_username",
  "scheme": "$remita_scheme" 

}
DATA;
        
     
curl_setopt($curl, CURLOPT_POSTFIELDS, $data);

//for debug only!
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);

$resp = curl_exec($curl);
 
 //echo  $resp;
$err = curl_error($curl);
curl_close($curl);
if($err){
 
     echo json_encode(array("statusCode"=>201, "errorMessage"=>"Error Occured:".$err."."));  
}
    else
    {
        
        
        $resp = json_decode($resp, true);
        
    //echo $resp;
        $message = $resp['message'];
     
        if($message == "Login success")
        { 
			
			$token = $resp['token'];
            //$pin = $resp['user']['pin'];
           $id = $resp['user']['id'];
           $profileID = $resp['user']['profileID'];
 

$url = $remita_url."/itex/billers";
  

//for debug only!
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);

$resp = curl_exec($curl);
 
 $ch1 = curl_init();

curl_setopt($ch1, CURLOPT_URL, $url);
curl_setopt($ch1, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch1, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'Authorization: Bearer '.$token;
curl_setopt($ch1, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch1);
 //echo $result;

if (curl_errno($ch1)) {
    //echo 'Error:' . curl_error($ch1);
	
	 echo json_encode(array("statusCode"=>201, "errorMessage"=>"Error Occured:".curl_error($ch1)."."));  
}
else
{
	 $resp1 = json_decode($result, true);

    //var_dump($resp1);
        $status = false;
      //echo $resp1['message']." Coded";
        if(isset($resp1['code']) == "00")
        {
    //  echo sizeof($resp1['data']);
			
			
    for($i=0;$i<sizeof($resp1['data']);$i++)
    {
		 $category = $resp1['data'][$i]['category'];  
		
			   
			
			 
			 if($category == "Airtime")
			 {
				 
				  for($e=0;$e<sizeof($resp1['data'][$i]['billers']);$e++)
			  {
				  
				  $name = $resp1['data'][$i]['billers'][$e]['name'];  
				 
		//  echo $name." - ".$channel." <p>";
					  
					
					  if($name == $channel)
					  {
					 $service = $resp1['data'][$i]['billers'][$e]['service'];  
				  $accountType = $resp1['data'][$i]['billers'][$e]['accountType']; 
						  
						  $naration = $wynk_name." Airtime (".$service .") purchase of ".$amount." for ".$phone_number;
					//	 echo $naration;
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();
$url = $remita_url."/itex/purchase/vtu";
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n\"phone\": \"".$phone_number."\",\n  \"paymentMethod\": \"cash\",\n  \"service\": \"".$service."\",\n  \"amount\": \"".$amount."\",\n  \"clientReference\": \"".$clientReference ."\",\n  \"channel\": \"MOBILE\",\n  \"sourceAccountNumber\": \"".$wallet_number."\",\n  \"transactionPin\": \"".$pin."\",\n  \"narration\": \"".$naration."\",\n  \"redeemBonus\": false,\n  \"bonusAmount\": 0\n}");
 
 //echo  "{\n\"phone\": \"".$phone_number."\",\n  \"paymentMethod\": \"cash\",\n  \"service\": \"".$service."\",\n  \"amount\": \"".$amount."\",\n  \"clientReference\": \"".$clientReference ."\",\n  \"channel\": \"MOBILE\",\n  \"sourceAccountNumber\": \"".$wallet_number."\",\n  \"transactionPin\": \"".$pin."\",\n  \"narration\": \"".$naration."\",\n  \"redeemBonus\": false,\n  \"bonusAmount\": 0\n}";

$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'Authorization: Bearer '.$token;
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
					  
 
 //echo $result;				  
				
if (curl_errno($ch)) {
   // echo 'Error:' . curl_error($ch);
	
	 echo json_encode(array("statusCode"=>201, "errorMessage"=>"Error Occured:".curl_error($ch)."."));  
	
}
						  else
						  {
							  
			 $resp = json_decode($result, true);
							  
						$code = $resp['code'];	  
							  
						$message = $resp['message'];	  
							  //echo $result;	
 $sql = 	mysqli_query($conn,"INSERT INTO `t_log`(`code`, `log_details`, `status`, `created_date`, `registeredby`) VALUES('$clientReference','$message','1','$datetime','$wynkid') ")or die("ERROR OCCURED: ".mysqli_error($conn)); 	
											  
							  if($code == "00")
							  {
								  
								  $message2 = $resp['data']['message'];	
								  $amounting = $resp['data']['amount'];	
								  $ref = $resp['data']['ref'];	
								  $transactionID = $resp['data']['transactionID'];	
								  $reference = $resp['data']['reference'];	
								 // $clientReference = $resp['data']['clientReference'];	
								  $message_all = $message . " ".$message2;	
								  
 $sql = 	mysqli_query($conn,"INSERT INTO `transaction_information`(`code`,   `truck_owner`,  `amount`, `commissiononfee`,  `registeredby`, `created_date`, `message`, `status`, `customer` ,  `owners_share`, `means`, `narration`, `products`, `channel`,  `id_number`, `wallet_number`, `refs` ) VALUES('$clientReference','$wynkid','$amount','-','$wynkid', '$datetime','$message_all','1', '$phone_number', '0','wallet','$naration','Airtime Purchase','$channel','$phone_number','$wallet_number','$airtime') ")or die("ERROR OCCURED: ".mysqli_error($conn)); 	
							
								  
								  					
 $device_token=$myName->showName($conn, "SELECT `device_token` FROM `device_token` WHERE `account_number` = '$wynkid'"); 	
 	
		 
			
			
		 
			if(!empty($device_token))
			{
				
				$fcmSend->sendFCM($device_token, "Airtime Purchase Successfull",$naration, "3", $naration);
			}		
								  
								  
								  
								 // echo $result;
								  
 	echo json_encode(array("statusCode"=>200, "amounting"=>$amounting, "refference"=>$ref, "transaction_id"=>$transactionID, "reference"=>$reference, "client_reference"=>$clientReference));  							  
								  
	//echo $result;  							  
								  
							  }
							  else
							  {
								  
								  							  					
 $device_token=$myName->showName($conn, "SELECT `device_token` FROM `device_token` WHERE `account_number` = '$wynkid'"); 	
 	
		 
			
			
		 
			if(!empty($device_token))
			{
				
				$fcmSend->sendFCM($device_token, "Airtime Purchase Not Successfull",$message, "3", $message);
			}		
				
								  
								  
		 	echo json_encode(array("statusCode"=>201, "errorMessage"=>"Error: ".$message));  			  
							  }
							  
				/*			  
							  
{ "code" : "00", "message" : "VTU Purchase Successful", "data" : { "error" : false, "message" : "Airtime Purchase Successful", "amount" : "100", "ref" : "ITEX-TAMSVTU5F318D8131B64FYJEUB1361261", "date" : "2020-08-10 19:10:09", "transactionID" : "207124435341669", "responseCode" : "00", "reference" : "ITEX-TAMSVTU5F318D8131B64FYJEUB1361261", "sequence" : "207124435341669", "clientReference" : "asd4978716271752715157570" }, "metadata" : null }
							  */
							  
							  
						  }
curl_close($ch);
					  
					  
					   
					  }
					  
					  
 
					  
					  
					  
					  
			  }
				
			 }
			  
			 
			 
			 
		 //echo $category."<p>"; 	
			 
 }
			
			
			
			
			
 
	
	
	
	
	
	
	
	
	
}




}
     
            
            
             
        
    }
    }















}
else
{
	echo json_encode(array("statusCode"=>201, "errorMessage"=>"Error: Important Information Missing. Please check and try again."));  	    
}
 

?>

