runtime: php74
service: wynkcloudapi

runtime_config:
  document_root: .
  
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

- url: /picture/(.+\.(gif|png|jpg))$
  static_files: img/\1
  upload: picture/.*.(gif|png|jpg)$

#env_variables:
  #MYSQL_DSN: mysql:unix_socket=/cloudsql/wynkapp:europe-west1:wynkng-ride
  #MYSQL_DB: wynkng_ride
  #MYSQL_USER: wynkng_user
  #MYSQL_PASS: hollywood2019
  
beta_settings:
  cloud_sql_instances: wynkapp:europe-west1:wynkng-ride

