<?php 
header('Access-Control-Allow-Origin: *');
   date_default_timezone_set('Africa/Lagos');
	
 require_once('config/DB_config.php');
require_once('class_file.php');
require_once('fcm-send-function.php');
require_once('view-application-details.php');
 
 


$fcm = new FCM(); 
$fcmSend = new fcm();

 

$myName = new Name();


$json =  json_decode(file_get_contents('php://input'), true);

 
 $clientReference = date('dmY').rand(234,62662);
 
 
 
$phone_number = $json['phone_number']; 
$code = $json['code']; 
$service =  strtolower($json['service']); 
$productCode = $json['productCode']; 
$wallet_number = $json['wallet_number']; 
$wynkid = $json['wynkid'];  

/*
$phone_number = "08035538658"; 
$code = "50MB:55.0" ; 
$service = "mtndata"; //convert to small letters 
$productCode = "7f52ab777d367021fabccf8402e64a2991f6f5e6347babca01496ce704fad964d19852e09883daf331f87c5b0ca2c0e409e34d2c126b8c4b0ca81d74e0ec6ccb"; 
$wallet_number = "6553672257"; 
$wynkid = "WYNK61362372"; 
 */ 




if(!empty($wallet_number))
{
	
	 
        
       $remita_url = $myName->showName($conn, "SELECT `remita_url` FROM `application` WHERE 1");	
       $remita_username = $myName->showName($conn, "SELECT `remita_username` FROM `application` WHERE 1");		
       $remita_password = $myName->showName($conn, "SELECT `remita_password` FROM `application` WHERE 1");		
       $pin = $myName->showName($conn, "SELECT `pin` FROM `user_unit` WHERE `account_number` = '$wynkid'");		
       $wynk_name = $myName->showName($conn, "SELECT `name` FROM `user_unit` WHERE `account_number` = '$wynkid'");		
       
       $remita_username = $myName->showName($conn, "SELECT `phone` FROM `wallet_info` WHERE `registeredby` = '$wynkid' AND `phone` != ''  LIMIT 1 ");
	$remita_password  = $myName->showName($conn, "SELECT `password` FROM `wallet_info` WHERE `registeredby` = '$wynkid' AND `password` != ''  LIMIT 1");

   $remita_scheme = $myName->showName($conn, "SELECT `remita_scheme` FROM `application` WHERE 1");	
$url = $remita_url."/authenticate";

        
       
$curl = curl_init($url);
curl_setopt($curl, CURLOPT_URL, $url);
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

$headers = array(
   "accept: application/json",
   "Content-Type: application/json",
);
curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);

$data = <<<DATA
{
  "password": "$remita_password",
  "rememberMe": true,
  "username": "$remita_username",
  "scheme": "$remita_scheme",
  "deviceId": "64784844-hhhd748849-g7378382"

}
DATA;
        
     
curl_setopt($curl, CURLOPT_POSTFIELDS, $data);

//for debug only!
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);

$resp = curl_exec($curl);
 
 //echo  $resp;
$err = curl_error($curl);
curl_close($curl);
if($err){
 
     echo json_encode(array("statusCode"=>201, "errorMessage"=>"Error Occured:".$err."."));  
}
    else
    {
        
        
        $resp = json_decode($resp, true);
        
       // echo $resp;
        $message = $resp['message'];
     
        if($message == "Login success")
        { $token = $resp['token'];
             //$pin = $resp['user']['pin'];
           $id = $resp['user']['id'];
           $profileID = $resp['user']['profileID'];
 
  $naration = "Data Purchase ".$wallet_number."(".$wynk_name.") for ".$phone_number.". ".$code;
						  
						 // $naration = $wynk_name." ".$service;
						 
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();
$url = $remita_url."/itex/subscribe/data";



curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
//curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n\"phoneNumber\": \"".$phone_number."\",\n  \"paymentMethod\": \"wallet\",\n  \"service\": \"".$service."\",\n  \"amount\": \"".$amount."\",\n  \"clientReference\": \"".$clientReference ."\",\n  \"channel\": \"MOBILE\",\n  \"sourceAccountNumber\": \"".$wallet_number."\",\n  \"transactionPin\": \"".$pin."\",\n  \"narration\": \"".$naration."\",\n  \"redeemBonus\": false,\n  \"bonusAmount\": 0\n}");
						  
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"phone\": \"".$phone_number."\",\n  \"code\": \"".$code."\",\n  \"paymentMethod\": \"cash\",\n  \"service\": \"".$service."\",\n  \"clientReference\": \"".$clientReference."\",\n  \"productCode\": \"".$productCode."\",\n  \"card\": null,\n  \"sourceAccountNumber\": \"".$wallet_number."\",\n  \"transactionPin\": \"".$pin."\",\n  \"narration\": \"".$naration."\",\n  \"redeemBonus\": false,\n  \"bonusAmount\": \"0\"\n}");
						  
						  
 //echo  "{\n  \"phone\": \"".$phone_number."\",\n  \"code\": \"".$code."\",\n  \"paymentMethod\": \"cash\",\n  \"service\": \"".$service."\",\n  \"clientReference\": \"".$clientReference."\",\n  \"productCode\": \"".$productCode."\",\n  \"card\": null,\n  \"sourceAccountNumber\": \"".$wallet_number."\",\n  \"transactionPin\": \"".$pin."\",\n  \"narration\": \"".$naration."\",\n  \"redeemBonus\": false,\n  \"bonusAmount\": \"0\"\n}";	  
						  

$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'Authorization: Bearer '.$token;
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
					  
 //echo $result;				  
				
if (curl_errno($ch)) {
   // echo 'Error:' . curl_error($ch);
	
	 echo json_encode(array("statusCode"=>201, "errorMessage"=>"Error Occured:".curl_error($ch)."."));  
	
}
						  else
						  {
							  
			 $resp = json_decode($result, true);
							  
						$code = $resp['code'];	  
							  
						$message = $resp['message'];	  
							//  echo $result;	
							  
 					  if($code == "00")
							  {
				 // $amounting = $resp['data']['amount'];	
								//  $ref = $resp['data']['ref'];	
								 // $transactionID = $resp['data']['transactionID'];	
								  $narration_2 = $resp['data']['narration'];	
							//	  $clientReference = $resp['data']['clientReference'];	
								 // $description = $resp['data']['description'];	
								  $message_all = $message ;	
								  
//$sql = 	mysqli_query($conn,"INSERT INTO `transaction_information`(`code`,   `truck_owner`,  `amount`, `commissiononfee`,  `registeredby`, `created_date`, `message`, `status`, `customer` ,  `owners_share`, `means`) VALUES('$clientReference','$wynkid','$amounting','-','$wynkid', '$datetime','$message_all','1', '$phone_number', '0','wallet') ")or die("ERROR OCCURED: ".mysqli_error($conn)); 	
						  
						  
 $sql = mysqli_query($conn,"INSERT INTO `transaction_information`(`code`,   `truck_owner`,  `amount`, `commissiononfee`,  `registeredby`, `created_date`, `message`, `status`, `customer` ,  `owners_share`, `means`, `narration`, `products`, `channel`,  `id_number`, `wallet_number`, `refs` ) VALUES('$clientReference','$wynkid','$amount','-','$wynkid', '$datetime','$message_all','1', '$phone_number', '0','wallet','$naration','data','$service','$phone_number','$wallet_number','data') ")or die("ERROR OCCURED: ".mysqli_error($conn)); 	
							 
												  					
 $device_token=$myName->showName($conn, "SELECT `device_token` FROM `device_token` WHERE `account_number` = '$wynkid'"); 	
  if(!empty($device_token))
			{
				
				$fcmSend->sendFCM($device_token, "Data Purchase Successfull",$naration, "3", $naration);
			}		
								  
 		  
						  
								  
		echo json_encode(array("statusCode"=>200, "narration"=>$narration, "message"=>$message,"client_reference"=>$clientReference));  						  
	//echo $result;  							  
								  
							  }
							  else
							  {
								  
					echo json_encode(array("statusCode"=>201, "errorMessage"=>$message));  			  
							  }
							  
				/*			  
							  
{ "code" : "00", "message" : "VTU Purchase Successful", "data" : { "error" : false, "message" : "Airtime Purchase Successful", "amount" : "100", "ref" : "ITEX-TAMSVTU5F318D8131B64FYJEUB1361261", "date" : "2020-08-10 19:10:09", "transactionID" : "207124435341669", "responseCode" : "00", "reference" : "ITEX-TAMSVTU5F318D8131B64FYJEUB1361261", "sequence" : "207124435341669", "clientReference" : "asd4978716271752715157570" }, "metadata" : null }
							  */
							  
							  
						  }
curl_close($ch);
					  
					  
					   
					  }
					  
					  
 
					  
					  
					  
					  
			  }
				
		 
			  
			 
			 
			 
		 //echo $category."<p>"; 	
			 
 }
else
{
	
	echo json_encode(array("statusCode"=>201, "errorMessage"=>"Wallet Number Is Missing."));  			  
	
}
			
			
			
			
			
 
	
	
	
	
	
	
	
 


 





 
 

?>

