<?php 
header('Access-Control-Allow-Origin: *');
   date_default_timezone_set('Africa/Lagos');
	
 require_once('config/DB_config.php');
require_once('class_file.php');

$myName = new Name();


$json =  json_decode(file_get_contents('php://input'), true);

 
 // $account = $json['account']; 
$account = "7029697853"; 
//$channel = "MTN"; 
 

//$clientReference = date('dmY').rand(234,62662);
if(!empty($account))
{
	
	 
        
       $remita_url = $myName->showName($conn, "SELECT `remita_url` FROM `application` WHERE 1");	
       $remita_username = $myName->showName($conn, "SELECT `remita_username` FROM `application` WHERE 1");		
       $remita_password = $myName->showName($conn, "SELECT `remita_password` FROM `application` WHERE 1");		
     //  $pin = $myName->showName($conn, "SELECT `pin` FROM `user_unit` WHERE `account_number` = '$wynkid'");		
    //   $wynk_name = $myName->showName($conn, "SELECT `name` FROM `user_unit` WHERE `account_number` = '$wynkid'");		
       
     

   $remita_scheme = $myName->showName($conn, "SELECT `remita_scheme` FROM `application` WHERE 1");	
$url = $remita_url."/authenticate";

        
       
$curl = curl_init($url);
curl_setopt($curl, CURLOPT_URL, $url);
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

$headers = array(
   "accept: application/json",
   "Content-Type: application/json",
);
curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);

$data = <<<DATA
{
  "password": "$remita_password",
  "rememberMe": true,
  "username": "$remita_username",
  "scheme": "$remita_scheme",
  "deviceId": "64784844-hhhd748849-g7378382"

}
DATA;
        
     
curl_setopt($curl, CURLOPT_POSTFIELDS, $data);

//for debug only!
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);

$resp = curl_exec($curl);
 
 //echo  $resp;
$err = curl_error($curl);
curl_close($curl);
if($err){
 
     echo json_encode(array("statusCode"=>201, "errorMessage"=>"Error Occured: ".$err."."));  
}
    else
    {
        
        
        $resp = json_decode($resp, true);
        
        //echo $resp;
        $message = $resp['message'];
     
        if($message == "Login success")
        { $token = $resp['token'];
             //$pin = $resp['user']['pin'];
           $id = $resp['user']['id'];
           $profileID = $resp['user']['profileID'];
 
 
 
$url = $remita_url."/itex/internet/bundles";
  
		 
		 
		 
		 // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
//curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"service\": \"multichoice\",\n  \"type\": \"DSTV\"\n}");

		 
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"service\": \"smile\",\n  \"channel\": \"MOBILE\",\n  \"type\": \"account\",\n  \"account\": \"".$account."\"\n}");
		 
		 
		 
		 
$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'Authorization: Bearer '.$token;
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
		 

 
		 
		 			
if (curl_errno($ch)) {
   // echo 'Error:' . curl_error($ch);
	
	 echo json_encode(array("statusCode"=>201, "errorMessage"=>"Error Occured:".curl_error($ch)."."));  
	
}
						  else
						  {
							  
			 $resp = json_decode($result, true);
							  
						$code = $resp['code'];	  
							  
						$message = $resp['message'];	  
	 				  	    $json2 = '[';
							  
							  if($code == "00")
							  {
								  
								//   echo $result;
								  
								  
								  
								    foreach ($resp['data']['bundles'] as $data ) {
      							 	if(!empty($data['name']))
										{
											 $name = $data['name'];
										 $code = $data['code'];
										 $displayPrice = $data['displayPrice'];
										 $price = $data['price'];
										 $fee = $data['fee'];
										 $validity = $data['validity'];
											//echo $name."<p>";
										
										$json2 .= '{
    "name": "'.$name.'",
    "code": "'.$code.'",
    "displayPrice": "'.$displayPrice.'",
    "fee": "'.$fee.'",
    "validity": "'.$validity.'",
    "price": "'.$price.'"
    
},'; 
										
										
											
										}
										
										
								    
								   
								   
							   }
								  
								  
								  
								  
								 // $message2 = $resp['data']['message'];	
								  
										 //echo $result;  
								  
							/*	   foreach ($resp['data']['bouquets']as $data ) {
      							$code = $data['code'];
      							$name = $data['name'];
      							$amount = $data['amount'];
      							$primaryAmount = $data['primaryAmount'];
      
					// echo $amount."<p>"   ;
									   
									   
									   
									   									   
										   
$json2 .= '{
    "code": "'.$code.'",
    "name": "'.$name.'",
    "amount": "'.$amount.'",
    "primaryAmount": "'.$primaryAmount.'"
    
},'; 
									   
								   }*/
					 			  
											  
					$json2 .= "]";
	
	//echo $json2;
 	 
	 $json1 = '{
    "statusCode": 200,
    "message": '.$json2.'}';
	 
	  
 $json1 = substr_replace($json1, '', strrpos($json1, ','), 1);
 echo trim($json1);
  			 	   
								  
								  
							  }
						  }
								
		 
curl_close($ch);
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
 





}
}
}
 
  else
							  {
								  
					echo json_encode(array("statusCode"=>201, "errorMessage"=>"Important Field Left Empty."));  			  
							  }

?>

