<?php 
header('Access-Control-Allow-Origin: *');
   date_default_timezone_set('Africa/Lagos');
	
 require_once('config/DB_config.php');
require_once('class_file.php');

$myName = new Name();


$json =  json_decode(file_get_contents('php://input'), true);

 

 
  

   $wynkid = $json['wynkid'];  
  $cable_code = $json['code'];  //DSTV+FRN7E36
  $renew = false;  //true/false
  $productMonths = 1;   //1,2
  $totalAmount = $json['totalAmount'];  
  $productCode = $json['productCode'];  
  $sourceAccountNumber = $json['from_wallet'];  
 /*
$wynkid = "WYNK87627590";  
  $cable_code = "2020072927000" ;  //DSTV+FRN7E36
  $renew = false;  //true/false
  $productMonths = 1;   //1,2
  $totalAmount = "21000";  
  $productCode = "2020072925000";  
  $sourceAccountNumber = "1200212830";
 */
$clientReference=date("YmdGis").$wynkid;

   
 

 
if(!empty($wynkid))
{
	
	 
        
       $remita_url = $myName->showName($conn, "SELECT `remita_url` FROM `application` WHERE 1");	
       $fee = $myName->showName($conn, "SELECT `fee` FROM `application` WHERE 1");	
       $remita_username = $myName->showName($conn, "SELECT `remita_username` FROM `application` WHERE 1");		
       $remita_password = $myName->showName($conn, "SELECT `remita_password` FROM `application` WHERE 1");		
   $pin = $myName->showName($conn, "SELECT `pin` FROM `user_unit` WHERE `account_number` = '$wynkid'");		
  $wynk_name = $myName->showName($conn, "SELECT `name` FROM `user_unit` WHERE `account_number` = '$wynkid'");		
  $phone = $myName->showName($conn, "SELECT `phone` FROM `user_unit` WHERE `account_number` = '$wynkid'");		
  
    $remita_username = $myName->showName($conn, "SELECT `phone` FROM `wallet_info` WHERE `registeredby` = '$wynkid' AND `phone` != ''  LIMIT 1 ");
	$remita_password  = $myName->showName($conn, "SELECT `password` FROM `wallet_info` WHERE `registeredby` = '$wynkid' AND `password` != ''  LIMIT 1");
  
    
	$totalAmount  = ($totalAmount * $productMonths) + $fee;
     

   $remita_scheme = $myName->showName($conn, "SELECT `remita_scheme` FROM `application` WHERE 1");	
$url = $remita_url."/authenticate";

        
       
$curl = curl_init($url);
curl_setopt($curl, CURLOPT_URL, $url);
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

$headers = array(
   "accept: application/json",
   "Content-Type: application/json",
);
curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);

$data = <<<DATA
{
  "password": "$remita_password",
  "rememberMe": true,
  "username": "$remita_username",
  "scheme": "$remita_scheme" 

}
DATA;
        
     
curl_setopt($curl, CURLOPT_POSTFIELDS, $data);

//for debug only!
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);

$resp = curl_exec($curl);
 
 //echo  $resp;
$err = curl_error($curl);
curl_close($curl);
if($err){
 
     echo json_encode(array("statusCode"=>201, "errorMessage"=>"Error Occured: ".$err."."));  
}
    else
    {
        
        
        $resp = json_decode($resp, true);
        
        //echo $resp;
        $message = $resp['message'];
     
        if($message == "Login success")
        { $token = $resp['token'];
             //$pin = $resp['user']['pin'];
           $id = $resp['user']['id'];
           $profileID = $resp['user']['profileID'];
 
 
 
$url = $remita_url."/itex/subscribe/multichoice";
  
		 
		 
		 
		 // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
	 
		 
/*curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"service\": \"multichoice\",\n  \"channel\": \"MOBILE\",\n  \"type\": \"".$channel."\",\n  \"account\": \"".$account."\",\n  \"smartCardCode\": \"".$iuc."\"\n}");*/
		 
//curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"phone\": \"".$phone."\",\n  \"code\": \"".$cable_code."\",\n  \"renew\": \"".$renew."\",\n  \"paymentMethod\": \"cash\",\n  \"service\": \"multichoice\",\n  \"clientReference\": \"".$clientReference."\",\n  \"productMonths\": \"".$productMonths."\",\n  \"totalAmount\": \"".$totalAmount."\",\n  \"productCode\": \"".$productCode."\",\n  \"card\": {},\n  \"channel\": \"MOBILE\",\n  \"sourceAccountNumber\": \"".$sourceAccountNumber."\",\n  \"transactionPin\": \"".$pin."\",\n  \"narration\": \"subscribe\",\n  \"redeemBonus\": \"false\",\n  \"bonusAmount\"\": \"0\"\n}");
		 
		 
		 
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"phone\": \"".$phone."\",\n  \"code\": \"".$cable_code."\",\n  \"renew\": \"".$renew."\",\n  \"paymentMethod\": \"cash\",\n  \"service\": \"multichoice\",\n  \"clientReference\": \"".$clientReference."\",\n  \"productMonths\": \"".$productMonths."\",\n  \"totalAmount\": \"".$totalAmount."\",\n  \"productCode\": \"".$productCode."\",\n  \"card\": {},\n  \"channel\": \"MOBILE\",\n  \"sourceAccountNumber\": \"".$sourceAccountNumber."\",\n  \"transactionPin\": \"".$pin."\",\n  \"narration\": \"subscribe\",\n  \"redeemBonus\": \"false\",\n  \"bonusAmount\": \"0\"\n}");
		 
//echo "{\n  \"phone\": \"".$phone."\",\n  \"code\": \"".$cable_code."\",\n  \"renew\": \"".$renew."\",\n  \"paymentMethod\": \"cash\",\n  \"service\": \"multichoice\",\n  \"clientReference\": \"".$clientReference."\",\n  \"productMonths\": \"".$productMonths."\",\n  \"totalAmount\": \"".$totalAmount."\",\n  \"productCode\": \"".$productCode."\",\n  \"card\": {},\n  \"channel\": \"MOBILE\",\n  \"sourceAccountNumber\": \"".$sourceAccountNumber."\",\n  \"transactionPin\": \"".$pin."\",\n  \"narration\": \"subscribe\",\n  \"redeemBonus\": \"false\",\n  \"bonusAmount\": \"0\"\n}";
		 
		 
$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'Authorization: Bearer '.$token;
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
		 

 //echo $result;
		 
		 			
if (curl_errno($ch)) {
   // echo 'Error:' . curl_error($ch);
	
	 echo json_encode(array("statusCode"=>201, "errorMessage"=>"Error Occured:".curl_error($ch)."."));  
	
}
						  else
						  {
							  
			 $resp = json_decode($result, true);
							  
						$code = $resp['code'];	  
							  
						$message = $resp['message'];	  
	 				  	  //  $json2 = '[';
							  
							  if($code == "00")
							  {
								  /*{
  "code": "00",
  "message": "MultiChoice Subscription Successful",
  "data": {
    "error": false,
    "message": "Successful",
    "ref": "387851860",
    "amount": "1510",
    "bouquetCode": "FRN7E36",
    "bouquetName": "French Touch",
    "account": "7029697853",
    "externalReference": "84005497",
    "auditReferenceNumber": "44c9400a-32f1-4a27-91bb-f72a7c050f73",
    "date": "2020-08-10 21:12:53",
    "response": "",
    "responseCode": "00",
    "reference": "ITEX-MULTICHOICE5F31AA451E404QYPD6VKO56712|387851860",
    "sequence": "134415215165785",
    "clientReference": "asd4978716271752715157570"
  },
  "metadata": null
}*/
								  
								  	$message2 = $resp['data']['message'];
								   	$ref = $resp['data']['ref'];	
							 		$amount = $resp['data']['amount'];	
								  $bouquetCode =$resp['data']['bouquetCode'];
								  $bouquetName =$resp['data']['bouquetName'];
								  $account = $resp['data']['account'];
							 	$externalReference = $resp['data']['externalReference'];
								  
								  
      							$auditReferenceNumber =$resp['data']['auditReferenceNumber'];
      							$bouquetCode = $resp['data']['bouquetCode'];
      						
      							$reference = $resp['data']['reference'];
      							
      							$sequence = $resp['data']['sequence'];
      							$clientReference = $resp['data']['clientReference'];
      					 
      					
								  
								  $refs = $ref."///".$externalReference."///".$reference."///".$sequence;
								    $message_all = $message . " ".$message2;	
								  $product = $bouquetCode." ".$bouquetName;
								  
/* $sql = 	mysqli_query($conn,"INSERT INTO `transaction_information`(`code`,   `truck_owner`,  `amount`, `commissiononfee`,  `registeredby`, `created_date`, `message`, `status`, `customer` ,  `owners_share`, `means`, `refs`, `products` ) VALUES('$clientReference','$wynkid','$totalAmount','$fee','$wynkid', '$datetime','$message_all','1', '$wynk_name', '0','wallet','$refs','$product') ")or die("ERROR OCCURED: ".mysqli_error($conn)); 	*/
								  
 $sql = mysqli_query($conn,"INSERT INTO `transaction_information`(`code`,   `truck_owner`,  `amount`, `commissiononfee`,  `registeredby`, `created_date`, `message`, `status`, `customer` ,  `owners_share`, `means`, `narration`, `products`, `channel`,  `id_number`, `wallet_number` , `refs`) VALUES('$clientReference','$wynkid','$totalAmount','$fee','$wynkid', '$datetime','$message_all','1', '$cable_code', '0','wallet','$naration','$bouquetName','cable','$cable_code','$sourceAccountNumber','$product') ")or die("ERROR OCCURED: ".mysqli_error($conn)); 									  
								  
				 		  
 echo json_encode(array("statusCode"=>200, "message"=>$message_all, "ref"=>$ref, "bouquetName"=>$bouquetName, "externalReference"=>$externalReference, "bouquetCode"=>$bouquetCode, "bouquetCode"=>$bouquetCode, "description"=>$description, "account"=>$account, "type"=>$type, "basketId"=>$basketId, "productCode"=>$productCode, "message"=>$message));  							  
								  
								  
								  
								  
								  
								  
								  //echo $result;  
					/*			  
								   foreach ($resp['data']['bouquets']as $data ) {
      						
      
					// echo $amount."<p>"   ;
									   
									   
									   
									   									   
										   
$json2 .= '{
    "code": "'.$code.'",
    "name": "'.$name.'",
    "amount": "'.$amount.'",
    "primaryAmount": "'.$primaryAmount.'"
    
},'; 
									   
								   }
								  */
											  
					/*$json2 .= "]";
	
	//echo $json2;
 	 
	 $json1 = '{
    "statusCode": 200,
    "message": '.$json2.'}';
	 
	  
 $json1 = substr_replace($json1, '', strrpos($json1, ','), 1);
 echo trim($json1);*/
  			 	  
								  
								  
							  }
							  else{
								  
								  
								  echo json_encode(array("statusCode"=>201, "errorMessage"=>$message));  	
							  }
						  }
								
		 
curl_close($ch);
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
 





}
}
}
 
  else
							  {
								  
					echo json_encode(array("statusCode"=>201, "errorMessage"=>"Important Field Left Empty."));  			  
							  }

?>

