<?php



// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://walletdemo.remita.net/api/get-account-details/8978802422');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIrMjM0ODEyMzU4OTUxMSIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2Njk5MDY2Mzh9.bTLRntOK0TLdeKoiDt59_x5p2mcxf3olV-gxd3eeVvYPpUvcHPNyyIOs0uhokKNmQXQia8aWKcKw6KzVfk_YqA';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);


echo $result;

if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);





?>