<?php 
header('Access-Control-Allow-Origin: *');
   date_default_timezone_set('Africa/Lagos');
	
 require_once('config/DB_config.php');
require_once('class_file.php');

$myName = new Name();


$json =  json_decode(file_get_contents('php://input'), true);

 
$dob = $json['dob']; 
  $wynkid = $json['wynkid']; 
  // $wynkid = "WYNK74832498"; 
  //$pin = "1234"; 
 
$dob =   date("Y-m-d", strtotime($dob));    
//$clientReference = date('dmY').rand(234,62662);
if(!empty($wynkid))
{
	$phone = $myName->showName($conn, "SELECT `phone` FROM `wallet_info` WHERE `registeredby` = '$wynkid' AND `primary_wallet` = 1 AND `accountNumber` != '' ORDER BY `id` DESC LIMIT 1");	
	 
        
	

	
       $remita_url = $myName->showName($conn, "SELECT `remita_url` FROM `application` WHERE 1");	
       $remita_username = $myName->showName($conn, "SELECT `remita_username` FROM `application` WHERE 1");		
       $remita_password = $myName->showName($conn, "SELECT `remita_password` FROM `application` WHERE 1");		
     //  $pin = $myName->showName($conn, "SELECT `pin` FROM `user_unit` WHERE `account_number` = '$wynkid'");		
    //   $wynk_name = $myName->showName($conn, "SELECT `name` FROM `user_unit` WHERE `account_number` = '$wynkid'");		
       
     

   $remita_scheme = $myName->showName($conn, "SELECT `remita_scheme` FROM `application` WHERE 1");	
$url = $remita_url."/authenticate";

        
       
$curl = curl_init($url);
curl_setopt($curl, CURLOPT_URL, $url);
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

$headers = array(
   "accept: application/json",
   "Content-Type: application/json",
);
curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);

$data = <<<DATA
{
  "password": "$remita_password",
  "rememberMe": true,
  "username": "$remita_username",
  "scheme": "$remita_scheme",
  "deviceId": "64784844-hhhd748849-g7378382"

}
DATA;
        
     
curl_setopt($curl, CURLOPT_POSTFIELDS, $data);

//for debug only!
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);

$resp = curl_exec($curl);
 
 //echo  $resp;
$err = curl_error($curl);
curl_close($curl);
if($err){
 
     echo json_encode(array("statusCode"=>201, "errorMessage"=>"Error Occured: ".$err."."));  
}
    else
    {
        
        
        $resp = json_decode($resp, true);
        
        //echo $resp;
        $message = $resp['message'];
     
        if($message == "Login success")
        { $token = $resp['token'];
             //$pin = $resp['user']['pin'];
           $id = $resp['user']['id'];
           $profileID = $resp['user']['profileID'];
 
 
 
$url = $remita_url."/account/update-pin";
  
		 
		 
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"phoneNumber\": \"".$phone."\",\n  \"dateOfBirth\": \"".$dob."\"\n}");
//curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"phoneNumber\": \""++"\",\n  \"newPin\": \"1234\"\n}");
		 
		 
$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'Authorization: Bearer '.$token;
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
 
//	echo $result;	 
		 
		 
		 
		 			
if (curl_errno($ch)) {
   // echo 'Error:' . curl_error($ch);
	
	 echo json_encode(array("statusCode"=>201, "errorMessage"=>"Error Occured:".curl_error($ch)."."));  
	
}
						  else
						  {
							  
			 $resp = json_decode($result, true);
							  
						$code = $resp['code'];	  
							  
						$message = $resp['message'];	  
	 				  	    $json2 = '[';
							  
							  if($code == "00")
							  {
			 			
$uuid = uniqid('', true);

$salt = sha1(rand());
        $salt = substr($salt, 0, 10);
        $encrypted = base64_encode(sha1($pin . $salt, true) . $salt);
        $hash = array("salt" => $salt, "encrypted" => $encrypted);
         
        $encrypted_password = $hash["encrypted"]; // encrypted password
        $salt = $hash["salt"]; // salt
		
		
		
		$number = 0;
		// WHERE `account_number` = '$account_number'
		
		
 $sql = "UPDATE `user_unit` SET  `dob` = '$dob' WHERE `account_number` = '$wynkid' ";
								  
								  
								  
								  
 $process = mysqli_query($conn, $sql) or die(mysqli_error($conn));
 
	if ($process) {
		
echo json_encode(array("statusCode"=>200, "errorMessage"=>"Pin Changed Successfully. Thank You."));  		
	}
								  else
								  {
									  
									echo json_encode(array("statusCode"=>201, "errorMessage"=>"Pin Not Changed Successfully. Please check and trry again later"));  		  
									  
								  }
								  
								  
								  
 
								  
							  }
							  else{
								  
							echo json_encode(array("statusCode"=>201, "errorMessage"=>"Error: Pin Not Changed Successfully. Please check and trry again later"));  		  
									  	  
							  }
							  
						  }
								 // $message2 = $resp['data']['message'];	
								  
curl_close($ch);
		  		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
 





}
}
}
 
  else
							  {
								  
					echo json_encode(array("statusCode"=>201, "errorMessage"=>"Important Field Left Empty."));  			  
							  }

?>

