<?php

/*ini_set('display_startup_errors', 1);
ini_set('display_errors', 1);
error_reporting(-1);*/

header('Access-Control-Allow-Origin: *');
 
 

include("config/DB_config.php");
 
 include("SendingSMS.php");
 include("view-application-details.php");
include("class_file.php");
$myName = new Name();

 
$username  = "";
$json =  json_decode(file_get_contents('php://input'), true);
$username = $json['wynkid']; 
 $username = "WYNK74654117"; 

  $remita_url = $myName->showName($conn, "SELECT `remita_url` FROM `application` WHERE 1");	
     //, `remita_username`, `remita_password`, `, `remita_url` 
       $remita_username = $myName->showName($conn, "SELECT `remita_username` FROM `application` WHERE 1");		
       $remita_password = $myName->showName($conn, "SELECT `remita_password` FROM `application` WHERE 1");		
       
$remita_scheme = $myName->showName($conn, "SELECT `remita_scheme` FROM `application` WHERE 1");
 
 
 ///$username = "WYNK74832498";




if(!empty($username))
{
	
 //echo $remita_username. " ".$remita_password." ".$remita_scheme;
   	
$url = $remita_url."/authenticate";

        
       
$curl = curl_init($url);
curl_setopt($curl, CURLOPT_URL, $url);
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

$headers = array(
   "accept: application/json",
   "Content-Type: application/json",
);
curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);

$data = <<<DATA
{
  "password": "$remita_password",
  "rememberMe": true,
  "username": "$remita_username",
  "scheme": "$remita_scheme"

}
DATA;
   
   
  // echo $data;     
     
curl_setopt($curl, CURLOPT_POSTFIELDS, $data);

//for debug only!
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);

$resp = curl_exec($curl);
 
 echo  $resp." nothing is returned";
$err = curl_error($curl);
curl_close($curl);
if($err){
 
     echo json_encode(array("statusCode"=>201, "errorMessage"=>"Error Occured: ".$err."."));  
}
    else
    {
        
        
        $resp = json_decode($resp, true);
 // echo $resp;
        $message = $resp['message'];
     
        if($message == "Login success")
        { $token = $resp['token'];
             $pin = $resp['user']['pin'];
           $id = $resp['user']['id'];
           $profileID = $resp['user']['profileID'];
 
         }
    }
		 
		 
		 
 echo $token; 		 
	
	
	
	
$json1 = "";
	 
	 $query =  "SELECT `id`,`accountNumber`, `accountName`, `actualBalance` FROM `wallet_info` WHERE `registeredby` = '$username' AND  `status` = 1 ORDER BY `accountName` ASC";	
	
	
	
 $extract_distance = mysqli_query($conn, $query) or die(mysqli_error($conn));
		$count = mysqli_num_rows($extract_distance);
    if ($count > 0)
		  {
		      $json2 = '[';
 	 while ($row_distance=mysqli_fetch_row($extract_distance))
    {
  						  $id=$row_distance[0];
		  $accountNumber=$row_distance[1];
		  $accountName=$row_distance[2];
		  $actualBalance=$row_distance[3];
		
 //echo $accountNumber."<p>";	 

		$url = $remita_url."/get-account-details/".$accountNumber; 
		 
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'Authorization: Bearer '.$token;
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);


  echo $result;

if (curl_errno($ch)) {
  echo json_encode(array("statusCode"=>201, "errorMessage"=>"Error Occured: ".curl_error($ch)."."));  
}else{
	
$resp1 = json_decode($result, true);	
	
	 //var_dump($resp1);
        $status = false;
    //  echo $resp1['code'].".... Coded";
        if(isset($resp1['code']) == "success")
        {
     
    $status = $resp1['data']['status'];     
        $id = $resp1['data']['id'];
 $accountNumber = $resp1['data']['accountNumber'];
 $currentBalance = $resp1['data']['currentBalance'];
 $dateOpened = $resp1['data']['dateOpened'];
 $schemeId = $resp1['data']['schemeId'];
 $schemeName = $resp1['data']['schemeName'];
 $walletAccountTypeId = $resp1['data']['walletAccountTypeId'];
 $accountOwnerId = $resp1['data']['accountOwnerId'];
 $accountOwnerName = $resp1['data']['accountOwnerName'];
 $accountOwnerPhoneNumber = $resp1['data']['accountOwnerPhoneNumber'];
 $accountName = $resp1['data']['accountName'];
 $actualBalance = $resp1['data']['actualBalance'];
 $trackingRef = $resp1['data']['trackingRef'];
 $walletLimit = $resp1['data']['walletLimit'];
 $nubanAccountNo = $resp1['data']['nubanAccountNo'];
 $accountFullName = $resp1['data']['accountFullName'];
 $totalCustomerBalances = $resp1['data']['totalCustomerBalances']; 
			
			
			
			//echo  $accountOwnerName." / ".$currentBalance." / ".$accountName."<p>";
  
 //$sql = 	 "UPDATE `wallet_info` SET  `currentBalance` = '$currentBalance', `actualBalance` = '$actualBalance'  WHERE  `registeredby` = '$username' AND `accountNumber` = '$accountNumber'";
  //$process = mysqli_query($conn, $sql) or die(mysqli_error($conn));    
  
		
					$json2 .= '{
    "walletnumber": "'.$accountNumber.'",
    "walletname": "'.$accountName.'",
    "currentBalance": "'.number_format($currentBalance,2).'",
    "actualBalance": "'.number_format($actualBalance,2).'"
},'; 
			
			
		}
	
	
}
		 
		 
		 
curl_close($ch);


   		

			
				  
	}
	
	

	
	
	
	$json2 .= "]";
	
	//echo $json2;
	 
	 $json1 = '{
    "statusCode": 200,
    "message": '.$json2.'}';
	 
	  
 $json1 = substr_replace($json1, '', strrpos($json1, ','), 1);
 echo trim($json1);
  
  
  //echo substr($json1, 0, -4);
	  //echo rtrim($json1, ",");
       //echo json_encode(array("statusCode"=>200, "message"=>$json2));     
        
        
		  }
         else
         {
             
             echo json_encode(array("statusCode"=>201, "message"=>"No USER information registered yet."));  
         }
	 

 

	
}

 else
         {
             
             echo json_encode(array("statusCode"=>201, "message"=>"User WYNK ID is missing. Please check and try again later."));  
         }

































 
            

 
 
 










?>