<?php 
header('Access-Control-Allow-Origin: *');
   date_default_timezone_set('Africa/Lagos');
	
 require_once('config/DB_config.php');
require_once('class_file.php');

$myName = new Name();


$json =  json_decode(file_get_contents('php://input'), true);

/*{
  "service": "multichoice",
  "channel": "MOBILE",
  "type": "DSTV",
  "account": "7029697853",
  "smartCardCode": "30530035598"
}*/


 
  $channel = $json['channel']; //GOTV--DSTV
 $iuc = $json['smartCardCode'];  
 $account = $json['smartCardCode'];  



 /* 

 $channel = "GOTV";//GOTV--DSTV
 $iuc = "7532760734"; //GOTV--DSTV
 $account = "7532760734"; //GOTV--DSTV
$channel = "GOTV"; 

*/
//$clientReference = date('dmY').rand(234,62662);
if(!empty($channel))
{
	
	 
        
       $remita_url = $myName->showName($conn, "SELECT `remita_url` FROM `application` WHERE 1");	
       $remita_username = $myName->showName($conn, "SELECT `remita_username` FROM `application` WHERE 1");		
       $remita_password = $myName->showName($conn, "SELECT `remita_password` FROM `application` WHERE 1");		
     //  $pin = $myName->showName($conn, "SELECT `pin` FROM `user_unit` WHERE `account_number` = '$wynkid'");		
    //   $wynk_name = $myName->showName($conn, "SELECT `name` FROM `user_unit` WHERE `account_number` = '$wynkid'");		
       
     

   $remita_scheme = $myName->showName($conn, "SELECT `remita_scheme` FROM `application` WHERE 1");	
$url = $remita_url."/authenticate";

        
       
$curl = curl_init($url);
curl_setopt($curl, CURLOPT_URL, $url);
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

$headers = array(
   "accept: application/json",
   "Content-Type: application/json",
);
curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);

$data = <<<DATA
{
  "password": "$remita_password",
  "rememberMe": true,
  "username": "$remita_username",
  "scheme": "$remita_scheme",
  "deviceId": "64784844-hhhd748849-g7378382"

}
DATA;
        
     
curl_setopt($curl, CURLOPT_POSTFIELDS, $data);

//for debug only!
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);

$resp = curl_exec($curl);
 
 //echo  $resp;
$err = curl_error($curl);
curl_close($curl);
if($err){
 
     echo json_encode(array("statusCode"=>201, "errorMessage"=>"Error Occured: ".$err."."));  
}
    else
    {
        
        
        $resp = json_decode($resp, true);
        
        //echo $resp;
        $message = $resp['message'];
     
        if($message == "Login success")
        { $token = $resp['token'];
             //$pin = $resp['user']['pin'];
           $id = $resp['user']['id'];
           $profileID = $resp['user']['profileID'];
 
 
 
$url = $remita_url."/itex/validate/multichoice";
  
		 
		 
		 
		 // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
		 
		 
		 /*{
  "service": "multichoice",
  "channel": "MOBILE",
  "type": "DSTV",
  "account": "7029697853",
  "amount": "1.0",
  "smartCardCode": "02027317597"
}*/
		 
		 
//curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"service\": \"multichoice\",\"channel\": \"multichoice\",\n  \"type\": \"".$channel."\"\n}");
		 
		 
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"service\": \"multichoice\",\n  \"channel\": \"MOBILE\",\n  \"type\": \"".$channel."\",\n  \"account\": \"".$account."\",\n  \"smartCardCode\": \"".$iuc."\"\n}");
		 

$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'Authorization: Bearer '.$token;
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
		 

 //echo  $result ;
		 
		 			
if (curl_errno($ch)) {
   // echo 'Error:' . curl_error($ch);
	
	 echo json_encode(array("statusCode"=>201, "errorMessage"=>"Error Occured:".curl_error($ch)."."));  
	
}
						  else
						  {
							  
			 $resp = json_decode($result, true);
							  
						$code = $resp['code'];	  
							  
						$message = $resp['message'];	  
	 				  	  //  $json2 = '[';
							  
							  if($code == "00")
							  {
								  
								 $ref = $resp['data']['ref'];	
								  
						 
								  
					 	 $name = $resp['data']['name'];	
								 $unit = $resp['data']['unit'];	
							//	  	$code =  $resp['data']['code'];
      							$name = $resp['data']['name'];
      						//	$amount = $resp['data']['amount'];
      						//	$primaryAmount = $resp['data']['primaryAmount'];
      							$customerNumber =$resp['data']['customerNumber'];
      							$bouquetCode = $resp['data']['bouquetCode'];
      							$bouquetCode =$resp['data']['bouquetCode'];
      							$description = $resp['data']['description'];
      							$account = $resp['data']['account'];
      							$type = $resp['data']['type'];
      							$basketId = $resp['data']['basketId'];
      							$productCode = $resp['data']['productCode'];
      							$message = $resp['data']['message'];
								  
								// echo($prosductCode);
								 
					//	  echo $result;		  
echo json_encode(array("statusCode"=>200, "customer_name"=>$name, "ref"=>$ref, "unit"=>$unit, "customerNumber"=>$customerNumber, "bouquetCode"=>$bouquetCode, "bouquetCode"=>$bouquetCode, "description"=>$description, "account"=>$account, "type"=>$type, "basketId"=>$basketId, "productCode"=>$productCode, "message"=>$message));  							  
								  
								  
								  
								  
								  
								  
								  //echo $result;  
					/*			  
								   foreach ($resp['data']['bouquets']as $data ) {
      						
      
					// echo $amount."<p>"   ;
									   
									   
									   
									   									   
										   
$json2 .= '{
    "code": "'.$code.'",
    "name": "'.$name.'",
    "amount": "'.$amount.'",
    "primaryAmount": "'.$primaryAmount.'"
    
},'; 
									   
								   }
								  */
											  
					/*$json2 .= "]";
	
	//echo $json2;
 	 
	 $json1 = '{
    "statusCode": 200,
    "message": '.$json2.'}';
	 
	  
 $json1 = substr_replace($json1, '', strrpos($json1, ','), 1);
 echo trim($json1);*/
  			 	  
								  
								  
							  }
						  }
								
		 
curl_close($ch);
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
		 
 





}
}
}
 
  else
							  {
								  
					echo json_encode(array("statusCode"=>201, "errorMessage"=>"Important Field Left Empty."));  			  
							  }

?>

